// @generated by protoc-gen-connect-es v0.8.6 with parameter "target=ts,import_extension=.ts"
// @generated from file v1/suzu.proto (package suzu.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Empty, MethodKind } from "@bufbuild/protobuf";
import { GetBlogResponse, GetHealthResponse } from "./suzu_pb.ts";

/**
 * @generated from service suzu.v1.BlogService
 */
export const BlogService = {
  typeName: "suzu.v1.BlogService",
  methods: {
    /**
     * @generated from rpc suzu.v1.BlogService.GetBlog
     */
    getBlog: {
      name: "GetBlog",
      I: Empty,
      O: GetBlogResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc suzu.v1.BlogService.GetHealth
     */
    getHealth: {
      name: "GetHealth",
      I: Empty,
      O: GetHealthResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

