name: ci
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: checkout
        uses: actions/checkout@v3.5.0
      - id: setup-rust
        name: setup rust
        uses: ningenMe/setup-rustup@v0.3.0
      - id: cargo-build
        name: cargo build
        run: |
          cargo --version
          cargo build
        shell: bash
