name: ci
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: checkout
        uses: actions/checkout@v3.5.0
      - id: setup-rust
        name: setup rust
        uses: ningenMe/setup-rustup@v0.3.0
      - id: setup-infra
        name: setup infra
        run: |
          docker-compose -f ./infra/tool/docker-compose.yaml up -d
        shell: bash
      - id: cargo-build
        name: cargo build
        run: |
          DATABASE_URL=mysql://root:password@127.0.0.1:3306/blog cargo build
        shell: bash
