name: ci
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: checkout
        uses: actions/checkout@v3.5.0
      # - id: setup-infra
      #   name: setup infra
      #   run: |
      #     docker-compose -f ./infra/tool/docker-compose.yaml up -d
      #   shell: bash

      - id: setup-rustup
        name: setup rustup
        uses: ningenMe/setup-rustup@v1.1.0
        with:
          rust-version: 1.74.1
      - id: setup-protoc
        name: setup protoc
        uses: arduino/setup-protoc@v2
      - id: setup-openssl
        name: setup openssl
        run: |
          sudo apt-get install libssl-dev
          sudo apt-get install musl-tools
        shell: bash
      - id: cargo-build
        name: cargo build
        run: |
          rustup target add x86_64-unknown-linux-musl
          TARGET_CC=x86_64-linux-musl-gcc cargo build --target=x86_64-unknown-linux-musl
        shell: bash
